<?php

namespace Ocart\Contact\Enums;

use Ocart\Core\Library\Enum;
use Html;

class ContactStatusEnum extends Enum
{
    public const READ = 'read';
    public const UNREAD = 'unread';

    protected function init($value)
    {
        if (!$value) {
            $value = self::UNREAD;
        }

        parent::init($value); // TODO: Change the autogenerated stub
    }

    public function toHtml()
    {
        switch ($this->value) {
            case self::READ:
                return Html::tag('span', $this->getLabel($this->value), [
                    'class' => 'inline-flex items-center justify-center px-2 py-1 mr-2 text-xs font-bold leading-none text-white bg-green-600 rounded',
                ]);
            case self::UNREAD:
                return Html::tag('span', $this->getLabel($this->value), [
                    'class' => 'inline-flex items-center justify-center px-2 py-1 mr-2 text-xs font-bold leading-none text-white bg-yellow-400 rounded',
                ]);
            default:
                return '';
                break;
        }

        return "<label>{$this->value}</label>";
    }

    static function getLabel($value) {
        return trans('plugins/contact::contact.statuses.'.$value);
    }
}