<?php

namespace Ocart\Dashboard\Supports;

class BaseWidget extends AbstractDashboardWidget
{
    public function buildWidget()
    {
        parent::buildWidget(); // TODO: Change the autogenerated stub
    }
}