<?php

if (!defined('PAYMENT_METHODS_SETTINGS_PAGE')) {
    define('PAYMENT_METHODS_SETTINGS_PAGE', 'PAYMENT_METHODS_SETTINGS_PAGE');
}
if (!defined('PAYMENT_FILTER_ADDITIONAL_PAYMENT_METHODS')) {
    define('PAYMENT_FILTER_ADDITIONAL_PAYMENT_METHODS', 'PAYMENT_FILTER_ADDITIONAL_PAYMENT_METHODS');
}
