<?php

namespace Ocart\Ecommerce\Enums;

use Ocart\Core\Library\Enum;

class ShippingMethodEnum extends Enum
{
    public const DEFAULT = 'default';

    protected function init($value)
    {
        if (!$value) {
            $value = self::DEFAULT;
        }

        parent::init($value); // TODO: Change the autogenerated stub
    }

    public function toHtml()
    {

        return "<label>{$this->value}</label>";
    }

    static function getLabel($value) {
        return trans('core/base::enums.statuses.'.$value);
    }
}